name: Scrape Water Levels

on: [push]

permissions:
    contents: write

jobs:
  run_scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R packages
        uses: r-lib/actions/setup-renv@v2

      - name: Run scraper script
        run: |
          Rscript scrape-water-levels.R

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add water_level.parquet
          git commit -m 'Update water level file [bot]'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}